services:
  - type: web
    name: bg-dogadjaji
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_FRONTEND
        value: 'true'
      - key: DATABASE_URL
        sync: false
